[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.9.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
